#!/bin/bash
username=$(id -u -n 1000)
changeinterface() {
config="/home/$username/.config/polybar/config.ini" # Define polybar config file
eth() {
if=$(ip -br l | awk '$1 !~ "lo|vir|wl|tun" { print $1}') # Find user's eth interface
if [ -z "$if" ];then # is interface empty?
        # If there is no eth interface, do not do anything.
        exit
fi
defif="eth0"  # default eth interface in polybar config
sed -i "s/$defif/$if/g" "$config" # change default eth interface to yours
}
wlan() {
if=$(ip -br l | awk '$1 !~ "lo|vir|eth|en|tun" { print $1}') # Find user's wlan interface
if [ -z "$if" ];then # is interface empty?
        # If there is no wlan interface, do not do anything.
        exit
fi
defif="wlan0"  # default wlan interface in polybar config
sed -i "s/$defif/$if/g" "$config" # change default wlan interface to yours
}
# Run functions
eth
wlan
}
changeinterface
